### ISSUE TITLE
Laser not turning off

### ISSUE THREAD

**Issue by ripmyundies** [305engineering/Inkscape#1]
Hi, great plugin - really the best out there.

I'm finding the laser doesn't turn off at the end of the 'print'.  I'm assuming it's just not sending the turn off command

**Comment by oni305** [comment]
![1_bwfix_128_preview](https://cloud.githubusercontent.com/assets/4008421/7332091/cec6598e-eb2e-11e4-8812-e0fb3bfb0c4f.png)
Strange i've try with this image with B/W and it turn off
"M03; Laser ON
G01 X0.0 Y2.3 F200
M05; Laser OFF
G00 X0 Y0; home"

even with grayscale
"M03  S160 ; Laser ON
G01 X0.0 Y2.3 F200
M05; Laser OFF
G00 X0 Y0; home"

**Comment by oni305** [comment]
by the way  I'have reuploaded the file, try it now.

**Comment by ripmyundies** [comment]
Thank you sir.  The GCode looks correct, for some reason at the end  of the 'print' the laser remains on.  I'll investigate further and try some manual updates to the gcode to identify the cause
