### ISSUE TITLE
Issues with GRBL 9j Jtech Fork

### ISSUE THREAD

**Issue by cojarbi** [305engineering/Inkscape#10]
HI. I changed the board to try your plugging but im getting no results. Attached you will find desired and gcode output as seen on universal gcode sender
<img width="1098" alt="screen shot 2016-01-25 at 9 02 34 pm" src="https://cloud.githubusercontent.com/assets/16444438/12570632/5c7b0350-c3a7-11e5-8cb6-c4cb0ba0af17.png">
This is what UGC sees
<img width="644" alt="screen shot 2016-01-25 at 9 06 19 pm" src="https://cloud.githubusercontent.com/assets/16444438/12570645/8130abdc-c3a7-11e5-8b45-40271c6d1bc5.png">
also 
[Raster2laser_0003_Gray_256 copy.gcode.txt](https://github.com/305engineering/Inkscape/files/104320/Raster2laser_0003_Gray_256.copy.gcode.txt)
It dosent seem to use the engrave speed as it muves well bellow 3000 wen working.

Also how you control the maximun and minimun values for the laser power?

**Comment by oni305** [comment]
1)
The Gcode is OK. 
With universal gcode sender you see only the travel, not the  value of S 
I use this software to inspect the gcode  ( https://www.cncedit.com/Basicviewer/  Win only)
![gcode_ok](https://cloud.githubusercontent.com/assets/4008421/12589335/7eb132a8-c45d-11e5-99db-7f6e05b6885d.png)

2)
you have to edit the GRBL settings ( https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.9#grbl-settings )
in particular:
$110= (x max rate, mm/min)
$111= (y max rate, mm/min)
$112= (z max rate, mm/min)

3) 
Till now it depends only from the color of the image (0-255) , and by default GRBL use a value betwen 0 and 1000 for the spindle (S), so you have to recompile GRBL editing line 246 of "config.h" and set it to 255.0 :
#define SPINDLE_MAX_RPM 1000.0 // Max spindle RPM. This value is equal to 100% duty cycle on the PWM.

I've already scheduled, to add other function (power scaling , variable speed & support for Smothieboard gcode flavour ) but i'm pretty busy right now ..
