### ISSUE TITLE
Hangs

### ISSUE THREAD

**Issue by ripmyundies** [305engineering/Inkscape#3]
Hi, again thank you...this was all working very well.  Then I had to reinstall Windows 7 (x64) due to a disk failure.  

Everything works in inkscape, other .py extensions work ok...however this extension hangs whenever I click apply.  I've tried 32b and 64b versions of inkscape, and checked all files are present and there is R/W privileges.

So. a simple square, highlighted and click the 305 extension, dialog box asking for export dir, file name etc.  If I click apply the 'Raster 2 Laser GCode generator working" box appears but nothing else happens and the process doesn't respond.

Any ideas....I'm sure it's an error on my part as it all worked well before!

**Comment by oni305** [comment]
Hi.
Are you using the file downloaded after Apr 25, 2015  ?
