### ISSUE TITLE
Please add an option to omit comments

### ISSUE THREAD

**Issue by eoingriffin** [305engineering/Inkscape#6]
Comments generate a lot of extra text, increasing the file size and memory requirements of the gcode sender.
Large files will crash UniversalGcodeSender and (and chrome gcode-sender), but removing the comments can allow them to succeed.

I manually removed comments from a 150MB file to reduce it to 100MB and everything was smooth afterwards.

**Comment by oni305** [comment]
I'll work on it!

**Comment by eoingriffin** [comment]
Thanks!

**Comment by oni305** [comment]
i've removed the comments

**Comment by EoinGriffin-AI** [comment]
Great, thank you for making this software!
